version: "3"
services:
  web_app:
    build:
      context: .
      dockerfile: web_app/docker/rails/Dockerfile
    volumes:
      - ./web_app:/web_app

    ports:
      - 3001:3000
    depends_on:
      - web_app-mysql
  web_app_development:
    build:
      context: .
      dockerfile: web_app/docker/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: web_app-mysql
    ports:
      - 3306:3306
    volumes:
      - db-store-web_app:/var/lib/mysql
    platform: linux/amd64
volumes:
  db-store-web_app: