default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: test
  host: web_app-mysql
development:
  <<: *default
  database: web_app_development


test:
  <<: *default
  database: web_app_test


production:
  <<: *default
  database: web_app_production
  username: web_app
  password: <%= ENV["WEB_APP_DATABASE_PASSWORD"] %>
